### ISSUE TITLE
About the performance

### ISSUE THREAD

**Issue by LCorleone** [THUDM/cogdl#13]
Hi, thanks for the great job!
I simplify this project and remove the torch dependency, and plan to implement it under tf.
Now I have finished the algorithms of emb folder.  These are pure Python implementations. But my test results is poor. I find the default parameters in codes differ from the readme. So, could you please  clarify the parameters of the results displayed on your website？
Thanks a lot.

**Comment by qibinc** [comment]
Hi @LCorleone ,

Thanks for your attention on this work. Please use parameters in the README.

**Comment by LCorleone** [comment]
@qibinc Thanks for reply！
Some more questions.
1. Is the node feature dimension set to 128 for all unsupervised algorithms? The readme didn't mention.
2. The readme mentions that the expected Micro-F1 0.9 of line and netmf using wikipedia are 0.4 and 0.51, while in LEADERBOARD of your website, these two results are 0.49 and 0.58. Could you please explain this, or if I miss something? My results is 0.46 and 0.4 for line and netmf, which may be a little bit strange I think.
Thanks!

**Comment by lykeven** [comment]
We are sorry that it takes so long to response your questions..
1. For all unsupervised algorithms, we set the embedding dimension to 128 in evaluate task in order to make a fair comparison.
2.Due to the different parameter setting, these algorithms will have different performance. If you set `walk-length=80` and 
`walk-num=20` for line, you will get better performance than 0.49. As for NetMF, `window-size=1` will obtain a greater result `Micro-F1 = 0.59`
