### ISSUE TITLE
Issues loading TU dataset

### ISSUE THREAD

**Issue by spencerfrazier** [THUDM/cogdl#224]
## ❓ Questions & Help

@THINK2TRY 

You were the last person to make significant edits to the TU dataloader. I am getting an error when loading what I believe to be correctly formatted data. I've been trying to debug for a while now. Any idea what is happening? I've attached the error along with my dataset. No worries if you don't have time to investigate, figured I'd ask in case I am missing something straightforward :)

![tu](https://user-images.githubusercontent.com/21336485/115090264-66d58980-9ee2-11eb-8ecd-7b6297d942ce.png)
[tu-format-gh.zip](https://github.com/THUDM/cogdl/files/6328133/tu-format-gh.zip)

**Comment by THINK2TRY** [comment]
@spencerfrazier 
Thanks for your attention to CogDL. It seems that your `principles_A.txt` is not constructed properly. TU dataset is for graph classification. The order of nodes in adjacency(or edge_index) in TU Dataset is accumulated graph by graph, which is different from that in node classification. For example, if there is a dataset containing 2 graph both with 5 nodes and the edge lists are as follows:
Graph 1: [[0, 1], [1, 2], [3, 4]]
Graph 2: [[0, 3], [2, 4], [1, 2]]
Then the `*_A.txt` should look like this:
0, 1                          <----- Graph 1
1, 2                          <----- Graph 1
3, 4                          <----- Graph 1
5, 8                          <----- Graph 2
7, 9                          <----- Graph 2
6, 7                          <----- Graph 2
instead of 
0, 1
1, 2
3, 4
0, 3
2, 4
1, 2

I don't know whether your dataset is from a real scene or hand-constructed, but I think this might be the cause of your problem.
Hope this helps. 

Thank you again for your attention because we find another bug when testing : )

**Comment by spencerfrazier** [comment]
Thanks for your help! And glad I helped find another bug accidentally :) I was able to reformat the data and am getting far fewer errors constructing the graphs. Now I only get one "operation does not have an identity" error during graph creation (84th index in the particular node_slice).

I think this is throwing off training per the second screenshot (my indices are off by one). Any ideas? I have pulled the latest fixes you merged in. I've attached the updated data.

![Screenshot from 2021-04-17 12-15-28](https://user-images.githubusercontent.com/21336485/115119570-1b20ef80-9f77-11eb-8681-ee2a84d7054a.png)
![Screenshot from 2021-04-17 12-16-07](https://user-images.githubusercontent.com/21336485/115119571-1b20ef80-9f77-11eb-9407-680cef19567c.png)
[updated-tu-data.zip](https://github.com/THUDM/cogdl/files/6329594/updated-tu-data.zip)

**Comment by spencerfrazier** [comment]
Looks like index 84 got skipped in the graph indicator file somehow. I'll check the code that is generating this.

**Comment by spencerfrazier** [comment]
Unfortunately that wasnt the issue. Still getting the `size inconsistent with indices `error 

[tu-format-v3.zip](https://github.com/THUDM/cogdl/files/6329646/tu-format-v3.zip)

**Comment by spencerfrazier** [comment]
Resolved it - I didnt notice the re-indexing in tu_data.py:

`edge_index = read_file(folder, prefix, "A", torch.long).t() - 1
    batch = read_file(folder, prefix, "graph_indicator", torch.long) - 1`

This might cause some issues for people if they start their node/graph ids at 0. But for me it's solved and I'm finally training. Thanks!
